server:
  port: 8686
spring:
  profiles:
    active: dev
  application:
    name: dts-server
  dts:
    username: bitest
    password: zib2P2nas28QPni
    sid-name: dtseylk147826fdb6q
    group-name: bitest
    kafka-broker-url-name: dts-cn-hangzhou.aliyuncs.com:18001
    kafka-topic: cn_hangzhou_rm_bp1hddend5q83p03g_rdsdt_dtsacct
    initial-checkpoint-name: 1611826888    # 注意这里是秒的时间戳，默认是当前时间戳。第一次启动的时候会参考这个时间戳，后续以文件或者kafka的存储位点为主
    use-config-checkpoint-name: false       # 强制使用当前位点，这里使用的时候要特别注意，不是非得回滚到指定位点，不要用true，否则重启的时候会重复消费
    subscribe-mode-name: subscribe         # subscribe表示多机主备
    max-poll-records: 100
    include-data-info: # 数据过滤  包含数据信息
      bi: [ test01 ]  # marketing_db_prod : 对应的库名    [ all,abc ] 对应的表名 : all 代表所有表, abc 代表具体的表名
    exclude-data-info:
      xxl-job-admin: [all]
      exclude-table-change-field:
#         all: [ updated,updator ]
      table-partition-map:
        content_materials_label_rlat_info: 0
  kafka:
    bootstrap-servers: 172.31.117.188:9092
#      trust-store-password: KafkaOnsClient
    producer:
      security:
        protocol: SASL_SSL
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      partition: 0
    template:
      default-topic: info
#java:
#  security:
#    auth:
#      login:
#        config: /Users/tandemac/workspace/dts/dts-server/src/main/resources/kafka_client_jaas.conf                     # 基于阿里云提供的
#        trust-store-location: /Users/tandemac/workspace/dts/dts-server/src/main/resources/kafka.client.truststore.jks  # 基于阿里云提供参考 : https://help.aliyun.com/document_detail/99958.html?spm=a2c4g.11186623.2.14.4c2a30f0KEj6Av#concept-99958-zh
